file(READ ${CMAKE_ARGV3} hexdata HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1, " PRIMITIV_OPENCL_KERNEL_CHAR_ARRAY ${hexdata})
file(WRITE ${CMAKE_ARGV4} ${PRIMITIV_OPENCL_KERNEL_CHAR_ARRAY})
